# nutrition_db.py

nutrition_db = {
    "AlooGobi": {"calories": 150, "carbs": 18, "protein": 4, "fat": 7, "vitamins": ["A", "C"]},
    "AlooMasala": {"calories": 180, "carbs": 25, "protein": 3, "fat": 8, "vitamins": ["B6", "C"]},
    "Bhatura": {"calories": 260, "carbs": 32, "protein": 6, "fat": 12, "vitamins": ["B1", "B3"]},
    "BhindiMasala": {"calories": 120, "carbs": 10, "protein": 3, "fat": 6, "vitamins": ["A", "C"]},
    "Biryani": {"calories": 292, "carbs": 45, "protein": 10, "fat": 8, "vitamins": ["B12"]},
    "Chai": {"calories": 72, "carbs": 12, "protein": 2, "fat": 2, "vitamins": ["B2"]},
    "Chole": {"calories": 210, "carbs": 30, "protein": 9, "fat": 6, "vitamins": ["B9"]},
    "CoconutChutney": {"calories": 150, "carbs": 8, "protein": 2, "fat": 13, "vitamins": ["E"]},
    "Dal": {"calories": 180, "carbs": 25, "protein": 9, "fat": 4, "vitamins": ["B9"]},
    "Dosa": {"calories": 133, "carbs": 18, "protein": 3, "fat": 5, "vitamins": ["B1"]},
    "DumAloo": {"calories": 200, "carbs": 28, "protein": 4, "fat": 9, "vitamins": ["C"]},
    "FishCurry": {"calories": 220, "carbs": 6, "protein": 20, "fat": 12, "vitamins": ["D", "B12"]},
    "Ghevar": {"calories": 350, "carbs": 45, "protein": 5, "fat": 18, "vitamins": []},
    "GreenChutney": {"calories": 50, "carbs": 4, "protein": 1, "fat": 2, "vitamins": ["A", "C"]},
    "GulabJamun": {"calories": 150, "carbs": 25, "protein": 3, "fat": 5, "vitamins": []},
    "Idli": {"calories": 58, "carbs": 12, "protein": 2, "fat": 0.4, "vitamins": ["B1"]},
    "Jalebi": {"calories": 310, "carbs": 70, "protein": 2, "fat": 10, "vitamins": []},
    "Kebab": {"calories": 250, "carbs": 5, "protein": 20, "fat": 15, "vitamins": ["B12"]},
    "Kheer": {"calories": 200, "carbs": 30, "protein": 6, "fat": 7, "vitamins": ["B2"]},
    "Kulfi": {"calories": 220, "carbs": 25, "protein": 5, "fat": 11, "vitamins": ["A", "D"]},
    "Lassi": {"calories": 150, "carbs": 18, "protein": 6, "fat": 5, "vitamins": ["B12"]},
    "MuttonCurry": {"calories": 300, "carbs": 8, "protein": 25, "fat": 20, "vitamins": ["B12", "D"]},
    "OnionPakoda": {"calories": 250, "carbs": 20, "protein": 4, "fat": 18, "vitamins": ["C"]},
    "PalakPaneer": {"calories": 180, "carbs": 12, "protein": 9, "fat": 10, "vitamins": ["A", "C"]},
    "Poha": {"calories": 180, "carbs": 30, "protein": 4, "fat": 6, "vitamins": ["B1"]},
    "RajmaCurry": {"calories": 210, "carbs": 35, "protein": 10, "fat": 5, "vitamins": ["B9"]},
    "RasMalai": {"calories": 250, "carbs": 28, "protein": 8, "fat": 12, "vitamins": ["A"]},
    "Samosa": {"calories": 260, "carbs": 30, "protein": 4, "fat": 15, "vitamins": ["C"]},
    "ShahiPaneer": {"calories": 280, "carbs": 20, "protein": 10, "fat": 18, "vitamins": ["A", "D"]},
    "WhiteRice": {"calories": 130, "carbs": 28, "protein": 2, "fat": 0.3, "vitamins": ["B1"]}
}
